import React, { useState } from 'react';
import {
  Download,
  FileText,
  Search,
  CheckCircle,
  FileCheck,
  Calendar,
  Shield,
  BookOpen,
  ArrowDownToLine,
  Filter,
} from 'lucide-react';
import { DownloadFile } from '../types';

interface DownloadsSectionProps {
  files: DownloadFile[];
}

export const DownloadsSection: React.FC<DownloadsSectionProps> = ({ files }) => {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState('');
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [downloadToast, setDownloadToast] = useState<string | null>(null);

  const categories = [
    'All',
    'Admission Documents',
    'School Forms',
    'Newsletters',
    'School Calendar',
    'Policies',
    'Academic Documents',
    'Other Downloads',
  ];

  const filteredFiles = files.filter((file) => {
    const matchesCategory =
      selectedCategory === 'All' || file.category === selectedCategory;
    const matchesQuery =
      file.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      file.description.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesQuery;
  });

  const handleDownload = (file: DownloadFile) => {
    setDownloadingId(file.id);

    // Simulate reliable document download
    setTimeout(() => {
      setDownloadingId(null);
      setDownloadToast(`Downloaded: "${file.title}"`);

      // Create a virtual download trigger
      const dummyContent = `Maai-Mahiu Girls High School Official Document: ${file.title}\nCategory: ${file.category}\nDate: ${file.updatedDate}\n\nThis is an official document generated by Maai-Mahiu Girls High School, Nakuru County, Kenya.`;
      const blob = new Blob([dummyContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${file.title.replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setTimeout(() => setDownloadToast(null), 3500);
    }, 800);
  };

  return (
    <section id="downloads" className="py-20 bg-white border-b border-slate-200/80">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-12">
          <div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-emerald-800 mb-2">
            <span className="w-5 h-0.5 bg-amber-500 inline-block"></span>
            <span>Document Repository</span>
            <span className="w-5 h-0.5 bg-amber-500 inline-block"></span>
          </div>
          <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-bold text-slate-900 tracking-tight mb-4">
            Document Center & Downloads
          </h2>
          <p className="text-slate-600 text-sm sm:text-base leading-relaxed">
            Access official school admission packets, medical forms, code of conduct, newsletters,
            and academic reference calendars.
          </p>
        </div>

        {/* Search & Category Filter Controls */}
        <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 mb-10">
          <div className="flex flex-col md:flex-row items-center gap-4 justify-between mb-6">
            {/* Search Input */}
            <div className="relative w-full md:max-w-md">
              <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search documents by keyword..."
                className="w-full pl-10 pr-4 py-2.5 text-xs sm:text-sm bg-white rounded-xl border border-slate-300 focus:outline-none focus:ring-2 focus:ring-emerald-700"
              />
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery('')}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-slate-400 hover:text-slate-600"
                >
                  Clear
                </button>
              )}
            </div>

            <div className="text-xs text-slate-500 font-mono self-end md:self-center">
              Showing {filteredFiles.length} of {files.length} documents
            </div>
          </div>

          {/* Category Tabs */}
          <div className="flex flex-wrap items-center gap-1.5">
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setSelectedCategory(cat)}
                className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-all whitespace-nowrap ${
                  selectedCategory === cat
                    ? 'bg-emerald-800 text-white shadow-xs'
                    : 'bg-white text-slate-600 hover:text-slate-900 border border-slate-200'
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* Document Items List */}
        {filteredFiles.length === 0 ? (
          <div className="text-center py-16 bg-slate-50 rounded-2xl border border-dashed border-slate-300">
            <FileText className="w-10 h-10 text-slate-400 mx-auto mb-3" />
            <p className="font-serif font-bold text-slate-700 text-lg mb-1">
              No documents matched your criteria
            </p>
            <p className="text-xs text-slate-500">
              Try adjusting your search terms or clearing the category filter.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {filteredFiles.map((file) => (
              <div
                key={file.id}
                className="bg-white p-5 rounded-xl border border-slate-200 hover:border-emerald-300 hover:shadow-md transition-all duration-200 flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <div className="flex items-center gap-2.5">
                      <div className="w-9 h-9 rounded-lg bg-emerald-50 text-emerald-800 flex items-center justify-center shrink-0 border border-emerald-100">
                        <FileCheck className="w-5 h-5" />
                      </div>
                      <div>
                        <span className="text-[10px] font-mono uppercase tracking-wider text-amber-700 font-semibold">
                          {file.category}
                        </span>
                        <h3 className="font-serif font-bold text-sm sm:text-base text-slate-900 leading-snug">
                          {file.title}
                        </h3>
                      </div>
                    </div>
                  </div>

                  <p className="text-xs text-slate-600 leading-relaxed mb-4 pl-11">
                    {file.description}
                  </p>
                </div>

                <div className="pl-11 pt-3 border-t border-slate-100 flex items-center justify-between">
                  <div className="flex items-center gap-2 text-[11px] text-slate-400 font-mono">
                    <span className="text-slate-600 font-semibold">{file.fileType}</span>
                    <span>·</span>
                    <span>{file.fileSize}</span>
                    <span>·</span>
                    <span>{file.updatedDate}</span>
                  </div>

                  <button
                    onClick={() => handleDownload(file)}
                    disabled={downloadingId === file.id}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-emerald-900 bg-emerald-50 hover:bg-emerald-100 active:bg-emerald-200 rounded-md border border-emerald-200 transition-colors"
                  >
                    <ArrowDownToLine className="w-3.5 h-3.5" />
                    <span>{downloadingId === file.id ? 'Downloading...' : 'Download'}</span>
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Toast Alert */}
        {downloadToast && (
          <div className="fixed bottom-6 right-6 z-50 bg-emerald-950 text-white px-5 py-3 rounded-xl shadow-2xl border border-emerald-700 flex items-center gap-3 animate-in slide-in-from-bottom-5">
            <CheckCircle className="w-5 h-5 text-amber-400 shrink-0" />
            <p className="text-xs font-semibold">{downloadToast}</p>
          </div>
        )}
      </div>
    </section>
  );
};
